spring.application.name=stock-sync-service
server.port=4001

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:/data/stockdb;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Vendor A Service Configuration
api.vendor.a.service.base-url=http://localhost:9000
api.vendor.a.service.get-products-uri=/vendor-a/products

# Vendor B Configuration - put it in a class path so that it can run in docker
file.vendor.b.csv.path=classpath:tmp/vendor-b/stock.csv

# set batch size for saveAll() method
spring.jpa.properties.hibernate.jdbc.batch_size=1000